# Generated by Django 5.0.7 on 2024-07-18 00:07

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=255)),
                ('altura', models.DecimalField(decimal_places=1, max_digits=8)),
                ('peso', models.DecimalField(decimal_places=1, max_digits=8)),
                ('tipo1', models.CharField(max_length=255)),
                ('tipo2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
