# Generated by Django 4.2.14 on 2024-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0002_pokemon_delete_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='imagem_url',
            field=models.CharField(default='https://static.wikia.nocookie.net/bec6f033-936d-48c5-9c1e-7fb7207e28af', max_length=255),
        ),
    ]
